#!/bin/sh

export PATH="~/.dotnet/tools:$PATH"
export PATH="/usr/local/share/dotnet:$PATH"

set -e

# Select files to format
FILES=$(git diff --cached --name-only --diff-filter=d)

if [ "$FILES" != "" ]
then    
    # Format all selected files
    echo $FILES | xargs dotnet format --include
    
    # Add back the modified files to staging
    echo $FILES | xargs git add
fi

exit 0
